id: IC42F59C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:12:51+00:00'
last_modified: '2022-06-10T05:30:26.310952+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ5668
  title: བདེ་མཆོག་ལཱུ་ཨི་པའི་ལུགས་ཀྱི་བསྐྱེད་རྫོགས་དམར་ཁྲིད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BE3D:
      image_group_id: I1KG1243
      title: Volume 1 of bde mchog lU i pa'i lugs kyi bskyed rdzogs dmar khrid
      total_pages: 352
      order: 1
      base_file: BE3D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
